apiVersion: "v1"
appVersion: ""
description: "Chart holding organization-operator."
icon: https://s.giantswarm.io/app-icons/organization-operator/1/dark.svg
home: "https://github.com/giantswarm/organization-operator"
name: "organization-operator"
version: "2.1.2"
annotations:
  io.giantswarm.application.audience: all
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "shield"
