apiVersion: "v1"
appVersion: "2.1.3"
description: "Chart holding organization-operator."
icon: https://s.giantswarm.io/app-icons/organization-operator/1/dark.svg
home: "https://github.com/giantswarm/organization-operator"
name: "organization-operator"
version: "2.1.3"
annotations:
  application.giantswarm.io/team: "shield"
  config.giantswarm.io/version: 1.x.x
